url: "https://rujunhan.github.io"
baseurl: ""

title: Rujun Han

author:
  name: Rujun Han

timezone: "America/Vancouver"
markdown: kramdown

kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE

plugins:
  - jekyll-sitemap
